<a href="https://colab.research.google.com/github/sravanthi773/DS-MACHINE-LEARNING/blob/main/Ds_ml_K_Fold_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_digits
digits=load_digits()
print("Dataset is loading")

Dataset is loading


In [3]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

digits=load_digits()

x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target, test_size=0.3)

print("splitting the data into train and test")



splitting the data into train and test


In [4]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

digits=load_digits()

x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target, test_size=0.3)

lr=LogisticRegression(solver="lbfgs",max_iter=3000)
lr.fit(x_train,y_train)
print(lr.score(x_test,y_test))


0.9722222222222222


In [6]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

digits=load_digits()

x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target, test_size=0.3)
svm=SVC()
svm.fit(x_train,y_train)

print(svm.score(x_test,y_test))



0.9814814814814815


In [7]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

digits=load_digits()

x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target, test_size=0.3)
rf=RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)

print(rf.score(x_test,y_test))



0.9629629629629629


In [2]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
print(kf)


KFold(n_splits=3, random_state=None, shuffle=False)


In [3]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [4]:
from sklearn.datasets import load_digits
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

digits=load_digits()

a=LogisticRegression(solver="lbfgs",max_iter=5000)
scores=cross_val_score(a,digits.data,digits.target,cv=3)

print(scores)


[0.91986644 0.94156928 0.91652755]


In [6]:
from sklearn.datasets import load_digits
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC

digits=load_digits()

b=SVC()
scores=cross_val_score(a,digits.data,digits.target,cv=3)

print(scores)




[0.91986644 0.94156928 0.91652755]


In [8]:
from sklearn.datasets import load_digits
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

digits=load_digits()

c=RandomForestClassifier(n_estimators=40)
scores=cross_val_score(a,digits.data,digits.target,cv=3)

print(scores)




[0.91986644 0.94156928 0.91652755]


In [12]:
from sklearn.datasets import load_digits
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import numpy as np


digits=load_digits()

a=LogisticRegression(solver="lbfgs",max_iter=5000)
b=SVC()
c=RandomForestClassifier(n_estimators=40)

scores1=cross_val_score(a,digits.data,digits.target,cv=3)
scores2=cross_val_score(b,digits.data,digits.target,cv=3)
scores3=cross_val_score(c,digits.data,digits.target,cv=3)

print(np.average(scores1))
print(np.average(scores2))
print(np.average(scores3))



0.9259877573734001
0.9699499165275459
0.9354479688369505
