<a href="https://colab.research.google.com/github/sravanthi773/DS-MACHINE-LEARNING/blob/main/ML_Train%26Test_datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
dataset=np.arange(10)
print(dataset)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
import numpy as np
from sklearn.model_selection import train_test_split

dataset=np.arange(10)
result=train_test_split(dataset)

print(dataset)
print(result)

[0 1 2 3 4 5 6 7 8 9]
[array([0, 9, 5, 4, 3, 7, 6]), array([2, 1, 8])]


In [5]:
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(20)
result=train_test_split(dataset)
print(dataset)
print(result)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[array([ 8, 17, 11,  7,  6, 15,  3, 12, 18, 13, 10,  1, 14, 19,  4]), array([ 0,  9, 16,  5,  2])]


In [7]:
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(10)
x_train,x_test=train_test_split(dataset)
print(dataset)
print()
print(x_train)
print(x_test)


[0 1 2 3 4 5 6 7 8 9]

[0 9 5 4 2 3 8]
[6 7 1]


In [8]:
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(10)
x_train,x_test=train_test_split(dataset,test_size=4)
print(dataset)
print()
print(x_train)
print(x_test)

[0 1 2 3 4 5 6 7 8 9]

[9 3 8 1 2 0]
[5 7 6 4]


In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(10)
x_train,x_test=train_test_split(dataset,test_size=4)
print(dataset)
print()
print(x_train)
print(x_test)

In [10]:
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(10)
x_train,x_test=train_test_split(dataset,test_size=0.5)
print(dataset)
print()
print(x_train)
print(x_test)

[0 1 2 3 4 5 6 7 8 9]

[4 6 3 8 0]
[1 5 2 9 7]


In [11]:
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(10)
x_train,x_test=train_test_split(dataset,train_size=6)
print(dataset)
print()
print(x_train)
print(x_test)

[0 1 2 3 4 5 6 7 8 9]

[1 9 8 7 3 2]
[4 6 0 5]


In [12]:
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(10)
x_train,x_test=train_test_split(dataset,train_size=6,test_size=4)
print(dataset)
print()
print(x_train)
print(x_test)

[0 1 2 3 4 5 6 7 8 9]

[9 1 4 8 0 7]
[3 2 5 6]


In [16]:
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(10)
x_train,x_test=train_test_split(dataset,train_size=4,test_size=4)
print(dataset)
print()
print(x_train)
print(x_test)

[0 1 2 3 4 5 6 7 8 9]

[6 2 7 0]
[9 3 8 5]


In [17]:
import numpy as np
dataset=np.arange(20)
print(dataset)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [19]:
import numpy as np
dataset=np.arange(20).reshape(2,10)
print(dataset)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [20]:
import numpy as np
dataset=np.arange(20).reshape(2,10).T
print(dataset)

[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]


In [21]:
import numpy as np
x=np.arange(10)
y=np.arange(20)
print(x)
print()
print(y)

[0 1 2 3 4 5 6 7 8 9]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [22]:
import numpy as np
x=np.arange(10).reshape(2,5)
y=np.arange(20).reshape(2,10).T
print(x)
print()
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]


In [24]:
import numpy as np
from sklearn.model_selection import train_test_split
x=np.arange(20).reshape(2,10).T
y=np.arange(10)
x_train,x_test,y_train,y_test=train_test_split(x,y)

print(x_train)
print()
print(x_test)
print()
print(y_train)
print()
print(y_test)

[[ 4 14]
 [ 3 13]
 [ 6 16]
 [ 0 10]
 [ 5 15]
 [ 9 19]
 [ 8 18]]

[[ 7 17]
 [ 1 11]
 [ 2 12]]

[4 3 6 0 5 9 8]

[7 1 2]


In [25]:
import numpy as np
from sklearn.model_selection import train_test_split
x=np.arange(20).reshape(2,10).T
y=np.arange(10)
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)

print(x_train)
print()
print(x_test)
print()
print(y_train)
print()
print(y_test)

[[ 9 19]
 [ 1 11]
 [ 6 16]
 [ 7 17]
 [ 3 13]
 [ 0 10]
 [ 5 15]]

[[ 2 12]
 [ 8 18]
 [ 4 14]]

[9 1 6 7 3 0 5]

[2 8 4]
